In [1]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\NEELSOFT\\Documents\\Python Scripts\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
#1.Create a null vector of size 10 but the fifth value which is 1.

Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#2.Create a vector with values ranging from 10 to 49.

Z=np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#3.Create a 3x3 matrix with values ranging from 0 to 8 

x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr=np.array([1,2,0,0,4,0])

print("Non-zero elements of the array arr:",arr[np.nonzero(arr)])


Non-zero elements of the array arr: [1 2 4]


In [7]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.025975352498357807 0.9862128827881799


In [6]:
#6. Create a random vector of size 30 and find the mean value.

Z = np.random.random(30)
m = Z.mean()
print(m)

0.4260491157003126
